"""
Standalone seed script — populates the Exercise table.
Run directly: python seed_data.py
Or called from main.py on startup when the table is empty.
"""
import json
import os
import sys

# Allow import when run directly from this directory
sys.path.insert(0, os.path.dirname(__file__))

from sqlmodel import Session, select
from database import engine, create_db_and_tables
from models import Exercise


# fmt: off
EXERCISES = [
    # ── CHEST (15) ──────────────────────────────────────────────────────────
    {
        "name": "Barbell Bench Press",
        "aliases": ["bench press", "flat bench"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment_required": ["barbell", "bench", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Classic horizontal push. Keep shoulder blades retracted and feet flat.",
    },
    {
        "name": "Incline Barbell Bench Press",
        "aliases": ["incline bench", "incline press"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment_required": ["barbell", "incline_bench", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "30-45° incline targets upper chest and anterior deltoid more.",
    },
    {
        "name": "Dumbbell Bench Press",
        "aliases": ["db bench", "dumbbell press"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment_required": ["dumbbells", "bench"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Greater ROM than barbell; each side works independently.",
    },
    {
        "name": "Incline Dumbbell Press",
        "aliases": ["incline db press"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment_required": ["dumbbells", "incline_bench"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Upper-chest emphasis with dumbbell freedom of movement.",
    },
    {
        "name": "Dumbbell Flye",
        "aliases": ["db flye", "chest flye"],
        "movement_pattern": "isolation",
        "primary_muscles": ["chest"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells", "bench"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Stretch-focused isolation. Keep slight elbow bend throughout.",
    },
    {
        "name": "Incline Dumbbell Flye",
        "aliases": ["incline flye"],
        "movement_pattern": "isolation",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders"],
        "equipment_required": ["dumbbells", "incline_bench"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Upper chest isolation with lengthened-position stretch.",
    },
    {
        "name": "Cable Crossover",
        "aliases": ["cable cross"],
        "movement_pattern": "isolation",
        "primary_muscles": ["chest"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": False,
        "notes": "Constant cable tension throughout the ROM.",
    },
    {
        "name": "Pec Deck Machine",
        "aliases": ["pec deck", "butterfly machine", "chest fly machine"],
        "movement_pattern": "isolation",
        "primary_muscles": ["chest"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Machine-guided adduction. Good for beginners learning the movement.",
    },
    {
        "name": "Machine Chest Press",
        "aliases": ["chest press machine", "hammer strength chest press"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment_required": ["machine"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Safer load drop; useful for high-rep or post-failure sets.",
    },
    {
        "name": "Push-Up",
        "aliases": ["pushup", "press-up"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment_required": ["bodyweight"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Bodyweight classic. Elevate feet to increase difficulty.",
    },
    {
        "name": "Decline Bench Press",
        "aliases": ["decline press"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["triceps"],
        "equipment_required": ["barbell", "bench", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Targets lower chest fibres; less shoulder involvement.",
    },
    {
        "name": "Dips (chest)",
        "aliases": ["chest dips", "forward-lean dips"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment_required": ["dip_bars"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Lean forward to bias chest over triceps.",
    },
    {
        "name": "Cable Flye High-to-Low",
        "aliases": ["high cable flye", "high to low flye"],
        "movement_pattern": "isolation",
        "primary_muscles": ["chest"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": False,
        "notes": "Cables set high; mimics decline motion for lower chest.",
    },
    {
        "name": "Cable Flye Low-to-High",
        "aliases": ["low cable flye", "low to high flye"],
        "movement_pattern": "isolation",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders"],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": False,
        "notes": "Cables set low; emphasises upper chest.",
    },
    {
        "name": "Landmine Press",
        "aliases": ["landmine chest press"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": False,
        "notes": "Arcing press path; shoulder-friendly alternative to flat bench.",
    },

    # ── BACK (20) ────────────────────────────────────────────────────────────
    {
        "name": "Conventional Deadlift",
        "aliases": ["deadlift", "conventional pull"],
        "movement_pattern": "hinge",
        "primary_muscles": ["back", "hamstrings", "glutes"],
        "secondary_muscles": ["traps", "forearms", "quads"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Full posterior chain. Brace hard, hinge not squat.",
    },
    {
        "name": "Romanian Deadlift",
        "aliases": ["RDL", "stiff-leg deadlift"],
        "movement_pattern": "hinge",
        "primary_muscles": ["hamstrings", "glutes"],
        "secondary_muscles": ["back", "forearms"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "hinge",
        "is_bilateral": True,
        "notes": "Hip hinge with slight knee bend; maximise hamstring stretch.",
    },
    {
        "name": "Barbell Row",
        "aliases": ["bent-over row", "BB row", "overhand row"],
        "movement_pattern": "pull",
        "primary_muscles": ["back", "lats"],
        "secondary_muscles": ["biceps", "traps"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Pronated grip, torso 45°. Pull to lower chest/upper abs.",
    },
    {
        "name": "Pendlay Row",
        "aliases": ["pendlay", "dead-stop row"],
        "movement_pattern": "pull",
        "primary_muscles": ["back", "lats"],
        "secondary_muscles": ["biceps", "traps"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Bar returned to floor each rep. Torso parallel to ground.",
    },
    {
        "name": "T-Bar Row",
        "aliases": ["t bar row", "chest-supported t-bar row"],
        "movement_pattern": "pull",
        "primary_muscles": ["back", "lats"],
        "secondary_muscles": ["biceps", "traps"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Neutral or close grip; strong mid-back stimulus.",
    },
    {
        "name": "Dumbbell Row",
        "aliases": ["DB row", "one-arm row", "single-arm row"],
        "movement_pattern": "pull",
        "primary_muscles": ["back", "lats"],
        "secondary_muscles": ["biceps", "traps"],
        "equipment_required": ["dumbbells", "bench"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": False,
        "notes": "Unilateral; full ROM, brace core against bench.",
    },
    {
        "name": "Cable Row",
        "aliases": ["seated cable row", "low cable row"],
        "movement_pattern": "pull",
        "primary_muscles": ["back", "lats"],
        "secondary_muscles": ["biceps"],
        "equipment_required": ["cable_machine"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Constant cable tension; great for mind-muscle connection.",
    },
    {
        "name": "Machine Row",
        "aliases": ["seated machine row", "hammer row"],
        "movement_pattern": "pull",
        "primary_muscles": ["back", "lats"],
        "secondary_muscles": ["biceps"],
        "equipment_required": ["machine"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Machine-guided path; useful for safe heavy sets.",
    },
    {
        "name": "Pull-Up",
        "aliases": ["pullup", "wide-grip pull-up"],
        "movement_pattern": "pull",
        "primary_muscles": ["lats", "back"],
        "secondary_muscles": ["biceps"],
        "equipment_required": ["pull_up_bar"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Pronated grip. Full hang at bottom, chin over bar at top.",
    },
    {
        "name": "Chin-Up",
        "aliases": ["chinup", "supinated pull-up"],
        "movement_pattern": "pull",
        "primary_muscles": ["lats", "biceps"],
        "secondary_muscles": ["back"],
        "equipment_required": ["pull_up_bar"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Supinated grip; greater biceps involvement than pull-up.",
    },
    {
        "name": "Lat Pulldown",
        "aliases": ["pulldown", "cable pulldown"],
        "movement_pattern": "pull",
        "primary_muscles": ["lats"],
        "secondary_muscles": ["biceps", "back"],
        "equipment_required": ["cable_machine"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Good pull-up substitute; adjustable load.",
    },
    {
        "name": "Wide-Grip Pulldown",
        "aliases": ["wide pulldown"],
        "movement_pattern": "pull",
        "primary_muscles": ["lats"],
        "secondary_muscles": ["back"],
        "equipment_required": ["cable_machine"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Wider grip shortens lats' active ROM; hit upper lats.",
    },
    {
        "name": "Straight-Arm Pulldown",
        "aliases": ["straight arm pulldown", "stiff-arm pulldown"],
        "movement_pattern": "isolation",
        "primary_muscles": ["lats"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Elbows locked; pure lat isolation. Great finisher.",
    },
    {
        "name": "Face Pull",
        "aliases": ["face pulls", "cable face pull"],
        "movement_pattern": "pull",
        "primary_muscles": ["shoulders", "traps"],
        "secondary_muscles": ["back"],
        "equipment_required": ["cable_machine"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Rope attachment at face height; external rotation focus.",
    },
    {
        "name": "Rack Pull",
        "aliases": ["rack pulls", "partial deadlift"],
        "movement_pattern": "hinge",
        "primary_muscles": ["back", "traps"],
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment_required": ["barbell", "rack"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Bar starts at knee height; heavy overload for upper back.",
    },
    {
        "name": "Trap Bar Deadlift",
        "aliases": ["hex bar deadlift", "trap bar pull"],
        "movement_pattern": "hinge",
        "primary_muscles": ["back", "quads", "glutes"],
        "secondary_muscles": ["hamstrings", "traps"],
        "equipment_required": ["trap_bar"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "More upright torso than conventional; more quad involvement.",
    },
    {
        "name": "Meadows Row",
        "aliases": ["meadows", "landmine row"],
        "movement_pattern": "pull",
        "primary_muscles": ["back", "lats"],
        "secondary_muscles": ["biceps", "traps"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": False,
        "notes": "End of landmine, staggered stance; great upper-back stretch.",
    },
    {
        "name": "Chest-Supported Row",
        "aliases": ["chest supported row", "incline row"],
        "movement_pattern": "pull",
        "primary_muscles": ["back", "lats"],
        "secondary_muscles": ["biceps"],
        "equipment_required": ["dumbbells", "incline_bench"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Chest on incline bench removes lower back demand.",
    },
    {
        "name": "Band Pull-Apart",
        "aliases": ["band pull apart", "pull apart"],
        "movement_pattern": "pull",
        "primary_muscles": ["traps", "shoulders"],
        "secondary_muscles": ["back"],
        "equipment_required": ["bands"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Rear delt and upper-back health drill. Use as warm-up or accessory.",
    },
    {
        "name": "Shrug",
        "aliases": ["barbell shrug", "dumbbell shrug"],
        "movement_pattern": "isolation",
        "primary_muscles": ["traps"],
        "secondary_muscles": [],
        "equipment_required": ["barbell"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Pure trap elevation. Pause at top.",
    },

    # ── SHOULDERS (12) ──────────────────────────────────────────────────────
    {
        "name": "Barbell Overhead Press",
        "aliases": ["OHP", "military press", "standing press"],
        "movement_pattern": "push",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": ["triceps", "traps"],
        "equipment_required": ["barbell", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Standing OHP builds full shoulder and core stability.",
    },
    {
        "name": "Dumbbell Overhead Press",
        "aliases": ["DB overhead press", "DB shoulder press", "seated DB press"],
        "movement_pattern": "push",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": ["triceps"],
        "equipment_required": ["dumbbells"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Can be seated or standing; each arm works independently.",
    },
    {
        "name": "Machine Shoulder Press",
        "aliases": ["shoulder press machine"],
        "movement_pattern": "push",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": ["triceps"],
        "equipment_required": ["machine"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Guided path allows heavier loads with less stability demand.",
    },
    {
        "name": "Arnold Press",
        "aliases": ["arnold"],
        "movement_pattern": "push",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": ["triceps"],
        "equipment_required": ["dumbbells"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Rotating press hits all three delt heads.",
    },
    {
        "name": "Lateral Raise",
        "aliases": ["dumbbell lateral raise", "side lateral raise", "side raise"],
        "movement_pattern": "isolation",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Lead with elbow, slight forward lean. Targets medial delt.",
    },
    {
        "name": "Cable Lateral Raise",
        "aliases": ["cable side raise"],
        "movement_pattern": "isolation",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": False,
        "notes": "Cable provides constant tension; better than dumbbells at bottom.",
    },
    {
        "name": "Machine Lateral Raise",
        "aliases": ["lateral raise machine"],
        "movement_pattern": "isolation",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Guided lateral raise; useful for high volume.",
    },
    {
        "name": "Front Raise",
        "aliases": ["dumbbell front raise", "plate front raise"],
        "movement_pattern": "isolation",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Anterior delt isolation. Often redundant if pressing heavy.",
    },
    {
        "name": "Rear Delt Flye",
        "aliases": ["reverse flye", "bent-over reverse flye", "rear delt raise"],
        "movement_pattern": "pull",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": ["traps"],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Bent over or lying prone; posterior delt and upper back.",
    },
    {
        "name": "Cable Rear Delt Flye",
        "aliases": ["cable reverse flye", "cable rear delt"],
        "movement_pattern": "pull",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": ["traps"],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": False,
        "notes": "Cross-cable or unilateral; constant tension on rear delt.",
    },
    {
        "name": "Upright Row",
        "aliases": ["barbell upright row", "cable upright row"],
        "movement_pattern": "pull",
        "primary_muscles": ["shoulders", "traps"],
        "secondary_muscles": ["biceps"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Wide grip reduces impingement risk. Pull to chin level.",
    },
    {
        "name": "Push Press",
        "aliases": ["push-press"],
        "movement_pattern": "push",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": ["triceps", "quads"],
        "equipment_required": ["barbell", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Leg drive to initiate; allows heavier loads than strict press.",
    },

    # ── BICEPS (10) ──────────────────────────────────────────────────────────
    {
        "name": "Barbell Curl",
        "aliases": ["BB curl", "standing barbell curl"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": ["forearms"],
        "equipment_required": ["barbell"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Supinated grip. Don't swing.",
    },
    {
        "name": "EZ Bar Curl",
        "aliases": ["ez curl", "EZ-bar curl"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": ["forearms"],
        "equipment_required": ["ez_bar"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Semi-supinated grip; easier on wrists than straight bar.",
    },
    {
        "name": "Dumbbell Curl",
        "aliases": ["DB curl", "alternating curl", "standing dumbbell curl"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": ["forearms"],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": False,
        "notes": "Supinate at top for full contraction.",
    },
    {
        "name": "Hammer Curl",
        "aliases": ["neutral curl"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": ["forearms"],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": False,
        "notes": "Neutral grip; targets brachialis and brachioradialis.",
    },
    {
        "name": "Cable Curl",
        "aliases": ["low cable curl", "cable bicep curl"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Constant cable tension throughout ROM.",
    },
    {
        "name": "Preacher Curl",
        "aliases": ["preacher", "scott curl"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": [],
        "equipment_required": ["ez_bar", "bench"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Arm supported on pad; isolates bicep, reduces cheat.",
    },
    {
        "name": "Concentration Curl",
        "aliases": ["concentration"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": False,
        "notes": "Seated, elbow on inner thigh; maximises peak contraction.",
    },
    {
        "name": "Incline Dumbbell Curl",
        "aliases": ["incline curl", "incline DB curl"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells", "incline_bench"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": False,
        "notes": "Arms behind body; maximum long-head stretch.",
    },
    {
        "name": "Machine Curl",
        "aliases": ["bicep curl machine"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Guided path; good drop-set tool.",
    },
    {
        "name": "Cross-Body Hammer Curl",
        "aliases": ["cross body curl"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": ["forearms"],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": False,
        "notes": "Curl across the body; emphasises brachialis.",
    },

    # ── TRICEPS (10) ─────────────────────────────────────────────────────────
    {
        "name": "Tricep Pushdown (rope)",
        "aliases": ["rope pushdown", "cable pushdown rope"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Flare hands at bottom for full lateral-head contraction.",
    },
    {
        "name": "Tricep Pushdown (bar)",
        "aliases": ["bar pushdown", "cable pushdown bar", "straight bar pushdown"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Straight or EZ bar; heavier than rope option.",
    },
    {
        "name": "Skull Crushers",
        "aliases": ["lying tricep extension", "EZ bar skull crusher"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": [],
        "equipment_required": ["ez_bar", "bench"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Lower bar to forehead/behind head. Long-head emphasis.",
    },
    {
        "name": "Close-Grip Bench Press",
        "aliases": ["CGBP", "narrow grip bench"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": ["chest", "shoulders"],
        "equipment_required": ["barbell", "bench", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Hands shoulder-width or slightly inside; tricep-focused press.",
    },
    {
        "name": "Overhead Tricep Extension (dumbbell)",
        "aliases": ["DB overhead extension", "dumbbell overhead tricep"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Arms overhead; strong long-head stretch. Can be single-arm.",
    },
    {
        "name": "Overhead Tricep Extension (cable)",
        "aliases": ["cable overhead extension", "rope overhead extension"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Face away from stack; continuous tension long-head stretch.",
    },
    {
        "name": "Diamond Push-Up",
        "aliases": ["triangle push-up", "close-grip push-up"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": ["chest"],
        "equipment_required": ["bodyweight"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Hands form a diamond; tricep dominant bodyweight push.",
    },
    {
        "name": "Dips (tricep)",
        "aliases": ["tricep dips", "bench dips", "parallel bar dips"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": ["chest", "shoulders"],
        "equipment_required": ["dip_bars"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Stay upright to bias triceps over chest.",
    },
    {
        "name": "Kickback",
        "aliases": ["tricep kickback", "DB kickback"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": False,
        "notes": "Hinge forward, extend arm back to full lockout.",
    },
    {
        "name": "JM Press",
        "aliases": ["JM", "J.M. press"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": ["chest"],
        "equipment_required": ["barbell", "bench", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Hybrid of skull crusher and close-grip bench; heavy tricep builder.",
    },

    # ── QUADS (12) ───────────────────────────────────────────────────────────
    {
        "name": "Barbell Back Squat",
        "aliases": ["back squat", "squat"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings", "back"],
        "equipment_required": ["barbell", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "High or low bar; king of lower body compounds.",
    },
    {
        "name": "Front Squat",
        "aliases": ["barbell front squat"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads"],
        "secondary_muscles": ["glutes", "back"],
        "equipment_required": ["barbell", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "More upright torso; heavier quad emphasis than back squat.",
    },
    {
        "name": "Hack Squat",
        "aliases": ["machine hack squat"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads"],
        "secondary_muscles": ["glutes"],
        "equipment_required": ["machine"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Feet forward on platform; high quad isolation with support.",
    },
    {
        "name": "Leg Press",
        "aliases": ["45 degree leg press", "machine leg press"],
        "movement_pattern": "push",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment_required": ["leg_press"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Foot position determines quad vs glute emphasis.",
    },
    {
        "name": "Bulgarian Split Squat",
        "aliases": ["BSS", "rear foot elevated split squat", "RFESS"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment_required": ["dumbbells", "bench"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": False,
        "notes": "Rear foot elevated; high hypertrophy stimulus per leg.",
    },
    {
        "name": "Lunge",
        "aliases": ["barbell lunge", "dumbbell lunge"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment_required": ["dumbbells"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": False,
        "notes": "Forward or reverse; step length adjusts quad/glute balance.",
    },
    {
        "name": "Walking Lunge",
        "aliases": ["walking lunges"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment_required": ["dumbbells"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": False,
        "notes": "Travelling variation; adds dynamic balance challenge.",
    },
    {
        "name": "Step-Up",
        "aliases": ["box step-up", "dumbbell step up"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment_required": ["dumbbells"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": False,
        "notes": "Drive through heel of working leg; avoid pushing off back foot.",
    },
    {
        "name": "Goblet Squat",
        "aliases": ["goblet"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["core"],
        "equipment_required": ["dumbbells"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Dumbbell/KB held at chest; great for learning squat mechanics.",
    },
    {
        "name": "Sissy Squat",
        "aliases": ["sissy"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads"],
        "secondary_muscles": [],
        "equipment_required": ["bodyweight"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Extreme knee travel; high rectus femoris stretch.",
    },
    {
        "name": "Leg Extension",
        "aliases": ["knee extension", "leg extension machine"],
        "movement_pattern": "isolation",
        "primary_muscles": ["quads"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Open-chain quad isolation; useful finisher.",
    },
    {
        "name": "Belt Squat",
        "aliases": ["belt squat machine"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment_required": ["machine"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Load via hip belt; spares spine. Great high-rep squat option.",
    },

    # ── HAMSTRINGS (8) ───────────────────────────────────────────────────────
    {
        "name": "Lying Leg Curl",
        "aliases": ["prone leg curl", "hamstring curl"],
        "movement_pattern": "isolation",
        "primary_muscles": ["hamstrings"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Prone position; full hamstring contraction.",
    },
    {
        "name": "Seated Leg Curl",
        "aliases": ["seated hamstring curl"],
        "movement_pattern": "isolation",
        "primary_muscles": ["hamstrings"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Seated; hip flexed so hamstrings work at longer length.",
    },
    {
        "name": "Nordic Curl",
        "aliases": ["nordic hamstring curl", "glute-ham raise"],
        "movement_pattern": "hinge",
        "primary_muscles": ["hamstrings"],
        "secondary_muscles": ["glutes"],
        "equipment_required": ["bodyweight"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Eccentric-heavy; extremely high injury-prevention value.",
    },
    {
        "name": "Good Morning",
        "aliases": ["good mornings", "barbell good morning"],
        "movement_pattern": "hinge",
        "primary_muscles": ["hamstrings", "back"],
        "secondary_muscles": ["glutes"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "hinge",
        "is_bilateral": True,
        "notes": "Bar on back, hinge at hip; teaches posterior chain tension.",
    },
    {
        "name": "Stiff-Leg Deadlift",
        "aliases": ["SLDL", "straight-leg deadlift"],
        "movement_pattern": "hinge",
        "primary_muscles": ["hamstrings"],
        "secondary_muscles": ["back", "glutes"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "hinge",
        "is_bilateral": True,
        "notes": "Minimal knee bend; more hamstring stretch than RDL.",
    },
    {
        "name": "Single-Leg Curl",
        "aliases": ["unilateral leg curl", "single leg hamstring curl"],
        "movement_pattern": "isolation",
        "primary_muscles": ["hamstrings"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": False,
        "notes": "Unilateral; identifies and corrects side-to-side imbalances.",
    },
    {
        "name": "Hip Extension Machine",
        "aliases": ["back extension machine", "hyperextension"],
        "movement_pattern": "hinge",
        "primary_muscles": ["hamstrings", "glutes"],
        "secondary_muscles": ["back"],
        "equipment_required": ["machine"],
        "mechanics": "compound",
        "force": "hinge",
        "is_bilateral": True,
        "notes": "Controlled hip extension; glutes or hamstrings depending on setup.",
    },
    {
        "name": "Sumo Deadlift",
        "aliases": ["sumo pull", "wide-stance deadlift"],
        "movement_pattern": "hinge",
        "primary_muscles": ["glutes", "hamstrings"],
        "secondary_muscles": ["back", "quads", "traps"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Wide stance, toes out; more glute/hip adductor, less lower back.",
    },

    # ── GLUTES (8) ───────────────────────────────────────────────────────────
    {
        "name": "Hip Thrust",
        "aliases": ["bodyweight hip thrust", "hip bridge"],
        "movement_pattern": "hinge",
        "primary_muscles": ["glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment_required": ["bench"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Upper back on bench; bodyweight or loaded. Squeeze at top.",
    },
    {
        "name": "Barbell Hip Thrust",
        "aliases": ["BB hip thrust", "loaded hip thrust"],
        "movement_pattern": "hinge",
        "primary_muscles": ["glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment_required": ["barbell", "bench"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Best loaded glute exercise; drive hips to full extension.",
    },
    {
        "name": "Glute Bridge",
        "aliases": ["floor glute bridge"],
        "movement_pattern": "hinge",
        "primary_muscles": ["glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment_required": ["bodyweight"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Floor-based hip thrust; lower ROM, good activation drill.",
    },
    {
        "name": "Cable Kickback",
        "aliases": ["cable glute kickback", "donkey kickback cable"],
        "movement_pattern": "isolation",
        "primary_muscles": ["glutes"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": False,
        "notes": "Ankle cuff on low cable; hip hyperextension at top.",
    },
    {
        "name": "Donkey Kick",
        "aliases": ["quadruped hip extension"],
        "movement_pattern": "isolation",
        "primary_muscles": ["glutes"],
        "secondary_muscles": [],
        "equipment_required": ["bodyweight"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": False,
        "notes": "On hands and knees; extend leg back/up. Add ankle weight.",
    },
    {
        "name": "Hip Abduction Machine",
        "aliases": ["abductor machine", "seated hip abduction"],
        "movement_pattern": "isolation",
        "primary_muscles": ["glutes"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Glute medius emphasis; seated machine.",
    },
    # RDL and Sumo Deadlift already in hamstrings/back — referenced by substitution_ids

    # ── CALVES (5) ───────────────────────────────────────────────────────────
    {
        "name": "Standing Calf Raise",
        "aliases": ["calf raise", "standing calf"],
        "movement_pattern": "isolation",
        "primary_muscles": ["calves"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Knee straight emphasises gastrocnemius.",
    },
    {
        "name": "Seated Calf Raise",
        "aliases": ["seated calf"],
        "movement_pattern": "isolation",
        "primary_muscles": ["calves"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Knee bent isolates soleus more than standing variation.",
    },
    {
        "name": "Leg Press Calf Raise",
        "aliases": ["calf press"],
        "movement_pattern": "isolation",
        "primary_muscles": ["calves"],
        "secondary_muscles": [],
        "equipment_required": ["leg_press"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "On leg press platform; allows heavy load.",
    },
    {
        "name": "Donkey Calf Raise",
        "aliases": ["donkey raise"],
        "movement_pattern": "isolation",
        "primary_muscles": ["calves"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Bent-over stance; long gastrocnemius stretch.",
    },
    {
        "name": "Single-Leg Calf Raise",
        "aliases": ["single leg calf", "one-leg calf raise"],
        "movement_pattern": "isolation",
        "primary_muscles": ["calves"],
        "secondary_muscles": [],
        "equipment_required": ["bodyweight"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": False,
        "notes": "Unilateral; doubled challenge, no equipment needed.",
    },

    # ── ABS / CORE (10) ──────────────────────────────────────────────────────
    {
        "name": "Plank",
        "aliases": ["front plank"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": ["shoulders"],
        "equipment_required": ["bodyweight"],
        "mechanics": "isolation",
        "force": "static",
        "is_bilateral": True,
        "notes": "Isometric anti-extension. Keep hips neutral.",
    },
    {
        "name": "Side Plank",
        "aliases": ["lateral plank"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": [],
        "equipment_required": ["bodyweight"],
        "mechanics": "isolation",
        "force": "static",
        "is_bilateral": False,
        "notes": "Lateral anti-flexion; targets obliques.",
    },
    {
        "name": "Ab Wheel Rollout",
        "aliases": ["ab wheel", "rollout"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": ["shoulders", "lats"],
        "equipment_required": ["bodyweight"],
        "mechanics": "compound",
        "force": "static",
        "is_bilateral": True,
        "notes": "Anti-extension; one of the hardest ab exercises.",
    },
    {
        "name": "Hanging Leg Raise",
        "aliases": ["hanging leg raises", "HLR"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": ["hip flexors"],
        "equipment_required": ["pull_up_bar"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Full leg raise or tuck version; posterior pelvic tilt at top.",
    },
    {
        "name": "Cable Crunch",
        "aliases": ["kneeling cable crunch"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Loaded crunch; progressive overload possible.",
    },
    {
        "name": "Decline Crunch",
        "aliases": ["decline situp", "decline crunch"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": [],
        "equipment_required": ["bench"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "On decline bench; greater ROM than flat crunch.",
    },
    {
        "name": "Russian Twist",
        "aliases": ["russian twists"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": [],
        "equipment_required": ["bodyweight"],
        "mechanics": "isolation",
        "force": "static",
        "is_bilateral": True,
        "notes": "Rotational; obliques and transverse abs. Add plate for load.",
    },
    {
        "name": "Pallof Press",
        "aliases": ["pallof", "anti-rotation press"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": ["shoulders"],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "static",
        "is_bilateral": False,
        "notes": "Anti-rotation; cable at shoulder height, press and hold.",
    },
    {
        "name": "Dead Bug",
        "aliases": ["dead bugs"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": [],
        "equipment_required": ["bodyweight"],
        "mechanics": "isolation",
        "force": "static",
        "is_bilateral": False,
        "notes": "Supine; opposite arm/leg extension with lumbar flat.",
    },
    {
        "name": "Dragon Flag",
        "aliases": ["dragon flags"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": ["lats"],
        "equipment_required": ["bench"],
        "mechanics": "compound",
        "force": "static",
        "is_bilateral": True,
        "notes": "Advanced; full body stays rigid while lowering from vertical.",
    },
]
# fmt: on


def _build_substitution_map(exercises: list[dict]) -> dict[str, list[int]]:
    """
    Build substitution_ids by grouping exercises that share the same
    primary muscle group and movement mechanics.  Within each group,
    every exercise substitutes every other exercise in the group.
    IDs are 1-based (matching the order of insertion).
    """
    groups: dict[str, list[int]] = {}
    for idx, ex in enumerate(exercises, start=1):
        pm = ex["primary_muscles"][0] if ex["primary_muscles"] else "other"
        mech = ex["mechanics"]
        key = f"{pm}_{mech}"
        groups.setdefault(key, []).append(idx)

    subs: dict[str, list[int]] = {}
    for idx, ex in enumerate(exercises, start=1):
        pm = ex["primary_muscles"][0] if ex["primary_muscles"] else "other"
        mech = ex["mechanics"]
        key = f"{pm}_{mech}"
        subs[str(idx)] = [i for i in groups[key] if i != idx]

    return subs


def seed(session: Session) -> None:
    subs_map = _build_substitution_map(EXERCISES)
    for idx, ex_data in enumerate(EXERCISES, start=1):
        ex = Exercise(
            name=ex_data["name"],
            aliases=json.dumps(ex_data.get("aliases", [])),
            movement_pattern=ex_data["movement_pattern"],
            primary_muscles=json.dumps(ex_data["primary_muscles"]),
            secondary_muscles=json.dumps(ex_data.get("secondary_muscles", [])),
            equipment_required=json.dumps(ex_data["equipment_required"]),
            mechanics=ex_data["mechanics"],
            force=ex_data["force"],
            is_bilateral=ex_data["is_bilateral"],
            notes=ex_data.get("notes", ""),
            substitution_ids=json.dumps(subs_map.get(str(idx), [])),
            is_custom=False,
        )
        session.add(ex)
    session.commit()
    print(f"Seeded {len(EXERCISES)} exercises.")


if __name__ == "__main__":
    create_db_and_tables()
    from sqlmodel import Session, select

    with Session(engine) as s:
        count = s.exec(select(Exercise)).all()
        if count:
            print("Exercises already seeded.")
        else:
            seed(s)
