"""
Standalone seed script — populates the Exercise table.
Run directly: python seed_data.py
Or called from main.py on startup when the table is empty.
"""
import json
import os
import sys

# Allow import when run directly from this directory
sys.path.insert(0, os.path.dirname(__file__))

from sqlmodel import Session, select
from database import engine, create_db_and_tables
from models import Exercise, SplitTemplate, SplitDay, MuscleVolumeLandmark


# fmt: off
EXERCISES = [
    # ── CHEST (15) ──────────────────────────────────────────────────────────
    {
        "name": "Barbell Bench Press",
        "aliases": ["bench press", "flat bench"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment_required": ["barbell", "bench", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Classic horizontal push. Keep shoulder blades retracted and feet flat.",
    },
    {
        "name": "Incline Barbell Bench Press",
        "aliases": ["incline bench", "incline press"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment_required": ["barbell", "incline_bench", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "30-45° incline targets upper chest and anterior deltoid more.",
    },
    {
        "name": "Dumbbell Bench Press",
        "aliases": ["db bench", "dumbbell press"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment_required": ["dumbbells", "bench"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Greater ROM than barbell; each side works independently.",
    },
    {
        "name": "Incline Dumbbell Press",
        "aliases": ["incline db press"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment_required": ["dumbbells", "incline_bench"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Upper-chest emphasis with dumbbell freedom of movement.",
    },
    {
        "name": "Dumbbell Flye",
        "aliases": ["db flye", "chest flye"],
        "movement_pattern": "isolation",
        "primary_muscles": ["chest"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells", "bench"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Stretch-focused isolation. Keep slight elbow bend throughout.",
    },
    {
        "name": "Incline Dumbbell Flye",
        "aliases": ["incline flye"],
        "movement_pattern": "isolation",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders"],
        "equipment_required": ["dumbbells", "incline_bench"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Upper chest isolation with lengthened-position stretch.",
    },
    {
        "name": "Cable Crossover",
        "aliases": ["cable cross"],
        "movement_pattern": "isolation",
        "primary_muscles": ["chest"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": False,
        "notes": "Constant cable tension throughout the ROM.",
    },
    {
        "name": "Pec Deck Machine",
        "aliases": ["pec deck", "butterfly machine", "chest fly machine"],
        "movement_pattern": "isolation",
        "primary_muscles": ["chest"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Machine-guided adduction. Good for beginners learning the movement.",
    },
    {
        "name": "Machine Chest Press",
        "aliases": ["chest press machine", "hammer strength chest press"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment_required": ["machine"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Safer load drop; useful for high-rep or post-failure sets.",
    },
    {
        "name": "Push-Up",
        "aliases": ["pushup", "press-up"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment_required": ["bodyweight"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Bodyweight classic. Elevate feet to increase difficulty.",
    },
    {
        "name": "Decline Bench Press",
        "aliases": ["decline press"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["triceps"],
        "equipment_required": ["barbell", "bench", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Targets lower chest fibres; less shoulder involvement.",
    },
    {
        "name": "Dips (chest)",
        "aliases": ["chest dips", "forward-lean dips"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment_required": ["dip_bars"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Lean forward to bias chest over triceps.",
    },
    {
        "name": "Cable Flye High-to-Low",
        "aliases": ["high cable flye", "high to low flye"],
        "movement_pattern": "isolation",
        "primary_muscles": ["chest"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": False,
        "notes": "Cables set high; mimics decline motion for lower chest.",
    },
    {
        "name": "Cable Flye Low-to-High",
        "aliases": ["low cable flye", "low to high flye"],
        "movement_pattern": "isolation",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders"],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": False,
        "notes": "Cables set low; emphasises upper chest.",
    },
    {
        "name": "Landmine Press",
        "aliases": ["landmine chest press"],
        "movement_pattern": "push",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": False,
        "notes": "Arcing press path; shoulder-friendly alternative to flat bench.",
    },

    # ── BACK (20) ────────────────────────────────────────────────────────────
    {
        "name": "Conventional Deadlift",
        "aliases": ["deadlift", "conventional pull"],
        "movement_pattern": "hinge",
        "primary_muscles": ["back", "hamstrings", "glutes"],
        "secondary_muscles": ["traps", "forearms", "quads", "abs"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Full posterior chain. Brace hard, hinge not squat.",
    },
    {
        "name": "Romanian Deadlift",
        "aliases": ["RDL", "stiff-leg deadlift"],
        "movement_pattern": "hinge",
        "primary_muscles": ["hamstrings", "glutes"],
        "secondary_muscles": ["back", "forearms", "abs"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "hinge",
        "is_bilateral": True,
        "notes": "Hip hinge with slight knee bend; maximise hamstring stretch.",
    },
    {
        "name": "Barbell Row",
        "aliases": ["bent-over row", "BB row", "overhand row"],
        "movement_pattern": "pull",
        "primary_muscles": ["back", "lats"],
        "secondary_muscles": ["biceps", "traps"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Pronated grip, torso 45°. Pull to lower chest/upper abs.",
    },
    {
        "name": "Pendlay Row",
        "aliases": ["pendlay", "dead-stop row"],
        "movement_pattern": "pull",
        "primary_muscles": ["back", "lats"],
        "secondary_muscles": ["biceps", "traps"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Bar returned to floor each rep. Torso parallel to ground.",
    },
    {
        "name": "T-Bar Row",
        "aliases": ["t bar row", "chest-supported t-bar row"],
        "movement_pattern": "pull",
        "primary_muscles": ["back", "lats"],
        "secondary_muscles": ["biceps", "traps"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Neutral or close grip; strong mid-back stimulus.",
    },
    {
        "name": "Dumbbell Row",
        "aliases": ["DB row", "one-arm row", "single-arm row"],
        "movement_pattern": "pull",
        "primary_muscles": ["back", "lats"],
        "secondary_muscles": ["biceps", "traps"],
        "equipment_required": ["dumbbells", "bench"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": False,
        "notes": "Unilateral; full ROM, brace core against bench.",
    },
    {
        "name": "Cable Row",
        "aliases": ["seated cable row", "low cable row"],
        "movement_pattern": "pull",
        "primary_muscles": ["back", "lats"],
        "secondary_muscles": ["biceps"],
        "equipment_required": ["cable_machine"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Constant cable tension; great for mind-muscle connection.",
    },
    {
        "name": "Machine Row",
        "aliases": ["seated machine row", "hammer row"],
        "movement_pattern": "pull",
        "primary_muscles": ["back", "lats"],
        "secondary_muscles": ["biceps"],
        "equipment_required": ["machine"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Machine-guided path; useful for safe heavy sets.",
    },
    {
        "name": "Pull-Up",
        "aliases": ["pullup", "wide-grip pull-up"],
        "movement_pattern": "pull",
        "primary_muscles": ["lats", "back"],
        "secondary_muscles": ["biceps", "abs"],
        "equipment_required": ["pull_up_bar"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Pronated grip. Full hang at bottom, chin over bar at top.",
    },
    {
        "name": "Chin-Up",
        "aliases": ["chinup", "supinated pull-up"],
        "movement_pattern": "pull",
        "primary_muscles": ["lats", "biceps"],
        "secondary_muscles": ["back", "abs"],
        "equipment_required": ["pull_up_bar"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Supinated grip; greater biceps involvement than pull-up.",
    },
    {
        "name": "Lat Pulldown",
        "aliases": ["pulldown", "cable pulldown"],
        "movement_pattern": "pull",
        "primary_muscles": ["lats"],
        "secondary_muscles": ["biceps", "back"],
        "equipment_required": ["cable_machine"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Good pull-up substitute; adjustable load.",
    },
    {
        "name": "Wide-Grip Pulldown",
        "aliases": ["wide pulldown"],
        "movement_pattern": "pull",
        "primary_muscles": ["lats"],
        "secondary_muscles": ["back", "biceps"],
        "equipment_required": ["cable_machine"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Wider grip shortens lats' active ROM; hit upper lats.",
    },
    {
        "name": "Straight-Arm Pulldown",
        "aliases": ["straight arm pulldown", "stiff-arm pulldown"],
        "movement_pattern": "isolation",
        "primary_muscles": ["lats"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Elbows locked; pure lat isolation. Great finisher.",
    },
    {
        "name": "Face Pull",
        "aliases": ["face pulls", "cable face pull"],
        "movement_pattern": "pull",
        "primary_muscles": ["shoulders", "traps"],
        "secondary_muscles": ["back"],
        "equipment_required": ["cable_machine"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Rope attachment at face height; external rotation focus.",
    },
    {
        "name": "Rack Pull",
        "aliases": ["rack pulls", "partial deadlift"],
        "movement_pattern": "hinge",
        "primary_muscles": ["back", "traps"],
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment_required": ["barbell", "rack"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Bar starts at knee height; heavy overload for upper back.",
    },
    {
        "name": "Trap Bar Deadlift",
        "aliases": ["hex bar deadlift", "trap bar pull"],
        "movement_pattern": "hinge",
        "primary_muscles": ["back", "quads", "glutes"],
        "secondary_muscles": ["hamstrings", "traps", "abs"],
        "equipment_required": ["trap_bar"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "More upright torso than conventional; more quad involvement.",
    },
    {
        "name": "Meadows Row",
        "aliases": ["meadows", "landmine row"],
        "movement_pattern": "pull",
        "primary_muscles": ["back", "lats"],
        "secondary_muscles": ["biceps", "traps"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": False,
        "notes": "End of landmine, staggered stance; great upper-back stretch.",
    },
    {
        "name": "Chest-Supported Row",
        "aliases": ["chest supported row", "incline row"],
        "movement_pattern": "pull",
        "primary_muscles": ["back", "lats"],
        "secondary_muscles": ["biceps"],
        "equipment_required": ["dumbbells", "incline_bench"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Chest on incline bench removes lower back demand.",
    },
    {
        "name": "Band Pull-Apart",
        "aliases": ["band pull apart", "pull apart"],
        "movement_pattern": "pull",
        "primary_muscles": ["traps", "shoulders"],
        "secondary_muscles": ["back"],
        "equipment_required": ["bands"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Rear delt and upper-back health drill. Use as warm-up or accessory.",
    },
    {
        "name": "Shrug",
        "aliases": ["barbell shrug", "dumbbell shrug"],
        "movement_pattern": "isolation",
        "primary_muscles": ["traps"],
        "secondary_muscles": [],
        "equipment_required": ["barbell"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Pure trap elevation. Pause at top.",
    },

    # ── SHOULDERS (12) ──────────────────────────────────────────────────────
    {
        "name": "Barbell Overhead Press",
        "aliases": ["OHP", "military press", "standing press"],
        "movement_pattern": "push",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": ["triceps", "traps", "abs"],
        "equipment_required": ["barbell", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Standing OHP builds full shoulder and core stability.",
    },
    {
        "name": "Dumbbell Overhead Press",
        "aliases": ["DB overhead press", "DB shoulder press", "seated DB press"],
        "movement_pattern": "push",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": ["triceps", "abs"],
        "equipment_required": ["dumbbells"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Can be seated or standing; each arm works independently.",
    },
    {
        "name": "Machine Shoulder Press",
        "aliases": ["shoulder press machine"],
        "movement_pattern": "push",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": ["triceps"],
        "equipment_required": ["machine"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Guided path allows heavier loads with less stability demand.",
    },
    {
        "name": "Arnold Press",
        "aliases": ["arnold"],
        "movement_pattern": "push",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": ["triceps"],
        "equipment_required": ["dumbbells"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Rotating press hits all three delt heads.",
    },
    {
        "name": "Lateral Raise",
        "aliases": ["dumbbell lateral raise", "side lateral raise", "side raise"],
        "movement_pattern": "isolation",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Lead with elbow, slight forward lean. Targets medial delt.",
    },
    {
        "name": "Cable Lateral Raise",
        "aliases": ["cable side raise"],
        "movement_pattern": "isolation",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": False,
        "notes": "Cable provides constant tension; better than dumbbells at bottom.",
    },
    {
        "name": "Machine Lateral Raise",
        "aliases": ["lateral raise machine"],
        "movement_pattern": "isolation",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Guided lateral raise; useful for high volume.",
    },
    {
        "name": "Front Raise",
        "aliases": ["dumbbell front raise", "plate front raise"],
        "movement_pattern": "isolation",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Anterior delt isolation. Often redundant if pressing heavy.",
    },
    {
        "name": "Rear Delt Flye",
        "aliases": ["reverse flye", "bent-over reverse flye", "rear delt raise"],
        "movement_pattern": "pull",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": ["traps"],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Bent over or lying prone; posterior delt and upper back.",
    },
    {
        "name": "Cable Rear Delt Flye",
        "aliases": ["cable reverse flye", "cable rear delt"],
        "movement_pattern": "pull",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": ["traps"],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": False,
        "notes": "Cross-cable or unilateral; constant tension on rear delt.",
    },
    {
        "name": "Upright Row",
        "aliases": ["barbell upright row", "cable upright row"],
        "movement_pattern": "pull",
        "primary_muscles": ["shoulders", "traps"],
        "secondary_muscles": ["biceps"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Wide grip reduces impingement risk. Pull to chin level.",
    },
    {
        "name": "Push Press",
        "aliases": ["push-press"],
        "movement_pattern": "push",
        "primary_muscles": ["shoulders"],
        "secondary_muscles": ["triceps", "quads"],
        "equipment_required": ["barbell", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Leg drive to initiate; allows heavier loads than strict press.",
    },

    # ── BICEPS (10) ──────────────────────────────────────────────────────────
    {
        "name": "Barbell Curl",
        "aliases": ["BB curl", "standing barbell curl"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": ["forearms"],
        "equipment_required": ["barbell"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Supinated grip. Don't swing.",
    },
    {
        "name": "EZ Bar Curl",
        "aliases": ["ez curl", "EZ-bar curl"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": ["forearms"],
        "equipment_required": ["ez_bar"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Semi-supinated grip; easier on wrists than straight bar.",
    },
    {
        "name": "Dumbbell Curl",
        "aliases": ["DB curl", "alternating curl", "standing dumbbell curl"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": ["forearms"],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": False,
        "notes": "Supinate at top for full contraction.",
    },
    {
        "name": "Hammer Curl",
        "aliases": ["neutral curl"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": ["forearms"],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": False,
        "notes": "Neutral grip; targets brachialis and brachioradialis.",
    },
    {
        "name": "Cable Curl",
        "aliases": ["low cable curl", "cable bicep curl"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Constant cable tension throughout ROM.",
    },
    {
        "name": "Preacher Curl",
        "aliases": ["preacher", "scott curl"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": [],
        "equipment_required": ["ez_bar", "bench"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Arm supported on pad; isolates bicep, reduces cheat.",
    },
    {
        "name": "Concentration Curl",
        "aliases": ["concentration"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": False,
        "notes": "Seated, elbow on inner thigh; maximises peak contraction.",
    },
    {
        "name": "Incline Dumbbell Curl",
        "aliases": ["incline curl", "incline DB curl"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells", "incline_bench"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": False,
        "notes": "Arms behind body; maximum long-head stretch.",
    },
    {
        "name": "Machine Curl",
        "aliases": ["bicep curl machine"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Guided path; good drop-set tool.",
    },
    {
        "name": "Cross-Body Hammer Curl",
        "aliases": ["cross body curl"],
        "movement_pattern": "pull",
        "primary_muscles": ["biceps"],
        "secondary_muscles": ["forearms"],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": False,
        "notes": "Curl across the body; emphasises brachialis.",
    },

    # ── TRICEPS (10) ─────────────────────────────────────────────────────────
    {
        "name": "Tricep Pushdown (rope)",
        "aliases": ["rope pushdown", "cable pushdown rope"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Flare hands at bottom for full lateral-head contraction.",
    },
    {
        "name": "Tricep Pushdown (bar)",
        "aliases": ["bar pushdown", "cable pushdown bar", "straight bar pushdown"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Straight or EZ bar; heavier than rope option.",
    },
    {
        "name": "Skull Crushers",
        "aliases": ["lying tricep extension", "EZ bar skull crusher"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": [],
        "equipment_required": ["ez_bar", "bench"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Lower bar to forehead/behind head. Long-head emphasis.",
    },
    {
        "name": "Close-Grip Bench Press",
        "aliases": ["CGBP", "narrow grip bench"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": ["chest", "shoulders"],
        "equipment_required": ["barbell", "bench", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Hands shoulder-width or slightly inside; tricep-focused press.",
    },
    {
        "name": "Overhead Tricep Extension (dumbbell)",
        "aliases": ["DB overhead extension", "dumbbell overhead tricep"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Arms overhead; strong long-head stretch. Can be single-arm.",
    },
    {
        "name": "Overhead Tricep Extension (cable)",
        "aliases": ["cable overhead extension", "rope overhead extension"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Face away from stack; continuous tension long-head stretch.",
    },
    {
        "name": "Diamond Push-Up",
        "aliases": ["triangle push-up", "close-grip push-up"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": ["chest"],
        "equipment_required": ["bodyweight"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Hands form a diamond; tricep dominant bodyweight push.",
    },
    {
        "name": "Dips (tricep)",
        "aliases": ["tricep dips", "bench dips", "parallel bar dips"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": ["chest", "shoulders"],
        "equipment_required": ["dip_bars"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Stay upright to bias triceps over chest.",
    },
    {
        "name": "Kickback",
        "aliases": ["tricep kickback", "DB kickback"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": [],
        "equipment_required": ["dumbbells"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": False,
        "notes": "Hinge forward, extend arm back to full lockout.",
    },
    {
        "name": "JM Press",
        "aliases": ["JM", "J.M. press"],
        "movement_pattern": "push",
        "primary_muscles": ["triceps"],
        "secondary_muscles": ["chest"],
        "equipment_required": ["barbell", "bench", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Hybrid of skull crusher and close-grip bench; heavy tricep builder.",
    },

    # ── QUADS (12) ───────────────────────────────────────────────────────────
    {
        "name": "Barbell Back Squat",
        "aliases": ["back squat", "squat"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings", "back", "abs", "calves"],
        "equipment_required": ["barbell", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "High or low bar; king of lower body compounds.",
    },
    {
        "name": "Front Squat",
        "aliases": ["barbell front squat"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads"],
        "secondary_muscles": ["glutes", "back", "abs", "calves"],
        "equipment_required": ["barbell", "rack"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "More upright torso; heavier quad emphasis than back squat.",
    },
    {
        "name": "Hack Squat",
        "aliases": ["machine hack squat"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads"],
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment_required": ["machine"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Feet forward on platform; high quad isolation with support.",
    },
    {
        "name": "Leg Press",
        "aliases": ["45 degree leg press", "machine leg press"],
        "movement_pattern": "push",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings", "calves"],
        "equipment_required": ["leg_press"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Foot position determines quad vs glute emphasis.",
    },
    {
        "name": "Bulgarian Split Squat",
        "aliases": ["BSS", "rear foot elevated split squat", "RFESS"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings", "calves"],
        "equipment_required": ["dumbbells", "bench"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": False,
        "notes": "Rear foot elevated; high hypertrophy stimulus per leg.",
    },
    {
        "name": "Lunge",
        "aliases": ["barbell lunge", "dumbbell lunge"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings", "calves"],
        "equipment_required": ["dumbbells"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": False,
        "notes": "Forward or reverse; step length adjusts quad/glute balance.",
    },
    {
        "name": "Walking Lunge",
        "aliases": ["walking lunges"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings", "calves"],
        "equipment_required": ["dumbbells"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": False,
        "notes": "Travelling variation; adds dynamic balance challenge.",
    },
    {
        "name": "Step-Up",
        "aliases": ["box step-up", "dumbbell step up"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment_required": ["dumbbells"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": False,
        "notes": "Drive through heel of working leg; avoid pushing off back foot.",
    },
    {
        "name": "Goblet Squat",
        "aliases": ["goblet"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["core"],
        "equipment_required": ["dumbbells"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Dumbbell/KB held at chest; great for learning squat mechanics.",
    },
    {
        "name": "Sissy Squat",
        "aliases": ["sissy"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads"],
        "secondary_muscles": [],
        "equipment_required": ["bodyweight"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Extreme knee travel; high rectus femoris stretch.",
    },
    {
        "name": "Leg Extension",
        "aliases": ["knee extension", "leg extension machine"],
        "movement_pattern": "isolation",
        "primary_muscles": ["quads"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Open-chain quad isolation; useful finisher.",
    },
    {
        "name": "Belt Squat",
        "aliases": ["belt squat machine"],
        "movement_pattern": "squat",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment_required": ["machine"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Load via hip belt; spares spine. Great high-rep squat option.",
    },

    # ── HAMSTRINGS (8) ───────────────────────────────────────────────────────
    {
        "name": "Lying Leg Curl",
        "aliases": ["prone leg curl", "hamstring curl"],
        "movement_pattern": "isolation",
        "primary_muscles": ["hamstrings"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Prone position; full hamstring contraction.",
    },
    {
        "name": "Seated Leg Curl",
        "aliases": ["seated hamstring curl"],
        "movement_pattern": "isolation",
        "primary_muscles": ["hamstrings"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Seated; hip flexed so hamstrings work at longer length.",
    },
    {
        "name": "Nordic Curl",
        "aliases": ["nordic hamstring curl", "glute-ham raise"],
        "movement_pattern": "hinge",
        "primary_muscles": ["hamstrings"],
        "secondary_muscles": ["glutes"],
        "equipment_required": ["bodyweight"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Eccentric-heavy; extremely high injury-prevention value.",
    },
    {
        "name": "Good Morning",
        "aliases": ["good mornings", "barbell good morning"],
        "movement_pattern": "hinge",
        "primary_muscles": ["hamstrings", "back"],
        "secondary_muscles": ["glutes"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "hinge",
        "is_bilateral": True,
        "notes": "Bar on back, hinge at hip; teaches posterior chain tension.",
    },
    {
        "name": "Stiff-Leg Deadlift",
        "aliases": ["SLDL", "straight-leg deadlift"],
        "movement_pattern": "hinge",
        "primary_muscles": ["hamstrings"],
        "secondary_muscles": ["back", "glutes", "abs"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "hinge",
        "is_bilateral": True,
        "notes": "Minimal knee bend; more hamstring stretch than RDL.",
    },
    {
        "name": "Single-Leg Curl",
        "aliases": ["unilateral leg curl", "single leg hamstring curl"],
        "movement_pattern": "isolation",
        "primary_muscles": ["hamstrings"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": False,
        "notes": "Unilateral; identifies and corrects side-to-side imbalances.",
    },
    {
        "name": "Hip Extension Machine",
        "aliases": ["back extension machine", "hyperextension"],
        "movement_pattern": "hinge",
        "primary_muscles": ["hamstrings", "glutes"],
        "secondary_muscles": ["back"],
        "equipment_required": ["machine"],
        "mechanics": "compound",
        "force": "hinge",
        "is_bilateral": True,
        "notes": "Controlled hip extension; glutes or hamstrings depending on setup.",
    },
    {
        "name": "Sumo Deadlift",
        "aliases": ["sumo pull", "wide-stance deadlift"],
        "movement_pattern": "hinge",
        "primary_muscles": ["glutes", "hamstrings"],
        "secondary_muscles": ["back", "quads", "traps", "abs"],
        "equipment_required": ["barbell"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Wide stance, toes out; more glute/hip adductor, less lower back.",
    },

    # ── GLUTES (8) ───────────────────────────────────────────────────────────
    {
        "name": "Hip Thrust",
        "aliases": ["bodyweight hip thrust", "hip bridge"],
        "movement_pattern": "hinge",
        "primary_muscles": ["glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment_required": ["bench"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Upper back on bench; bodyweight or loaded. Squeeze at top.",
    },
    {
        "name": "Barbell Hip Thrust",
        "aliases": ["BB hip thrust", "loaded hip thrust"],
        "movement_pattern": "hinge",
        "primary_muscles": ["glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment_required": ["barbell", "bench"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Best loaded glute exercise; drive hips to full extension.",
    },
    {
        "name": "Glute Bridge",
        "aliases": ["floor glute bridge"],
        "movement_pattern": "hinge",
        "primary_muscles": ["glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment_required": ["bodyweight"],
        "mechanics": "compound",
        "force": "push",
        "is_bilateral": True,
        "notes": "Floor-based hip thrust; lower ROM, good activation drill.",
    },
    {
        "name": "Cable Kickback",
        "aliases": ["cable glute kickback", "donkey kickback cable"],
        "movement_pattern": "isolation",
        "primary_muscles": ["glutes"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": False,
        "notes": "Ankle cuff on low cable; hip hyperextension at top.",
    },
    {
        "name": "Donkey Kick",
        "aliases": ["quadruped hip extension"],
        "movement_pattern": "isolation",
        "primary_muscles": ["glutes"],
        "secondary_muscles": [],
        "equipment_required": ["bodyweight"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": False,
        "notes": "On hands and knees; extend leg back/up. Add ankle weight.",
    },
    {
        "name": "Hip Abduction Machine",
        "aliases": ["abductor machine", "seated hip abduction"],
        "movement_pattern": "isolation",
        "primary_muscles": ["glutes"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Glute medius emphasis; seated machine.",
    },
    # RDL and Sumo Deadlift already in hamstrings/back — referenced by substitution_ids

    # ── CALVES (5) ───────────────────────────────────────────────────────────
    {
        "name": "Standing Calf Raise",
        "aliases": ["calf raise", "standing calf"],
        "movement_pattern": "isolation",
        "primary_muscles": ["calves"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Knee straight emphasises gastrocnemius.",
    },
    {
        "name": "Seated Calf Raise",
        "aliases": ["seated calf"],
        "movement_pattern": "isolation",
        "primary_muscles": ["calves"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Knee bent isolates soleus more than standing variation.",
    },
    {
        "name": "Leg Press Calf Raise",
        "aliases": ["calf press"],
        "movement_pattern": "isolation",
        "primary_muscles": ["calves"],
        "secondary_muscles": [],
        "equipment_required": ["leg_press"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "On leg press platform; allows heavy load.",
    },
    {
        "name": "Donkey Calf Raise",
        "aliases": ["donkey raise"],
        "movement_pattern": "isolation",
        "primary_muscles": ["calves"],
        "secondary_muscles": [],
        "equipment_required": ["machine"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": True,
        "notes": "Bent-over stance; long gastrocnemius stretch.",
    },
    {
        "name": "Single-Leg Calf Raise",
        "aliases": ["single leg calf", "one-leg calf raise"],
        "movement_pattern": "isolation",
        "primary_muscles": ["calves"],
        "secondary_muscles": [],
        "equipment_required": ["bodyweight"],
        "mechanics": "isolation",
        "force": "push",
        "is_bilateral": False,
        "notes": "Unilateral; doubled challenge, no equipment needed.",
    },

    # ── ABS / CORE (10) ──────────────────────────────────────────────────────
    {
        "name": "Plank",
        "aliases": ["front plank"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": ["shoulders"],
        "equipment_required": ["bodyweight"],
        "mechanics": "isolation",
        "force": "static",
        "is_bilateral": True,
        "notes": "Isometric anti-extension. Keep hips neutral.",
    },
    {
        "name": "Side Plank",
        "aliases": ["lateral plank"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": [],
        "equipment_required": ["bodyweight"],
        "mechanics": "isolation",
        "force": "static",
        "is_bilateral": False,
        "notes": "Lateral anti-flexion; targets obliques.",
    },
    {
        "name": "Ab Wheel Rollout",
        "aliases": ["ab wheel", "rollout"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": ["shoulders", "lats"],
        "equipment_required": ["bodyweight"],
        "mechanics": "compound",
        "force": "static",
        "is_bilateral": True,
        "notes": "Anti-extension; one of the hardest ab exercises.",
    },
    {
        "name": "Hanging Leg Raise",
        "aliases": ["hanging leg raises", "HLR"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": ["hip flexors"],
        "equipment_required": ["pull_up_bar"],
        "mechanics": "compound",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Full leg raise or tuck version; posterior pelvic tilt at top.",
    },
    {
        "name": "Cable Crunch",
        "aliases": ["kneeling cable crunch"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": [],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "Loaded crunch; progressive overload possible.",
    },
    {
        "name": "Decline Crunch",
        "aliases": ["decline situp", "decline crunch"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": [],
        "equipment_required": ["bench"],
        "mechanics": "isolation",
        "force": "pull",
        "is_bilateral": True,
        "notes": "On decline bench; greater ROM than flat crunch.",
    },
    {
        "name": "Russian Twist",
        "aliases": ["russian twists"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": [],
        "equipment_required": ["bodyweight"],
        "mechanics": "isolation",
        "force": "static",
        "is_bilateral": True,
        "notes": "Rotational; obliques and transverse abs. Add plate for load.",
    },
    {
        "name": "Pallof Press",
        "aliases": ["pallof", "anti-rotation press"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": ["shoulders"],
        "equipment_required": ["cable_machine"],
        "mechanics": "isolation",
        "force": "static",
        "is_bilateral": False,
        "notes": "Anti-rotation; cable at shoulder height, press and hold.",
    },
    {
        "name": "Dead Bug",
        "aliases": ["dead bugs"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": [],
        "equipment_required": ["bodyweight"],
        "mechanics": "isolation",
        "force": "static",
        "is_bilateral": False,
        "notes": "Supine; opposite arm/leg extension with lumbar flat.",
    },
    {
        "name": "Dragon Flag",
        "aliases": ["dragon flags"],
        "movement_pattern": "core",
        "primary_muscles": ["abs"],
        "secondary_muscles": ["lats"],
        "equipment_required": ["bench"],
        "mechanics": "compound",
        "force": "static",
        "is_bilateral": True,
        "notes": "Advanced; full body stays rigid while lowering from vertical.",
    },
]
# fmt: on

ALL_MUSCLES = ["chest", "back", "quads", "hamstrings", "glutes", "shoulders",
               "biceps", "triceps", "calves", "abs", "lats", "traps"]

# fmt: off
SPLITS = [
    {
        "name": "Full Body 2x",
        "slug": "full_body_2",
        "days_per_week": 2,
        "split_type": "full_body",
        "description": "Two full-body sessions per week, perfect for beginners or those with limited time. Each session hits every major muscle group.",
        "frequency_note": "1x/week per muscle — good starting point for beginners",
        "is_recommended": False,
        "days": [
            {"day_number": 1, "name": "Full Body A", "muscle_focus": ["chest", "back", "quads", "hamstrings", "glutes", "shoulders", "biceps", "triceps"]},
            {"day_number": 2, "name": "Full Body B", "muscle_focus": ["chest", "back", "quads", "hamstrings", "glutes", "shoulders", "biceps", "triceps"]},
        ],
    },
    {
        "name": "Upper / Lower 2x",
        "slug": "upper_lower_2",
        "days_per_week": 2,
        "split_type": "upper_lower",
        "description": "A simple two-day split alternating upper and lower body. Ideal when you can only train twice per week.",
        "frequency_note": "1x/week per muscle — minimal but functional",
        "is_recommended": False,
        "days": [
            {"day_number": 1, "name": "Upper", "muscle_focus": ["chest", "back", "shoulders", "biceps", "triceps"]},
            {"day_number": 2, "name": "Lower", "muscle_focus": ["quads", "hamstrings", "glutes", "calves"]},
        ],
    },
    {
        "name": "Full Body 3x",
        "slug": "full_body_3",
        "days_per_week": 3,
        "split_type": "full_body",
        "description": "Three full-body sessions per week with slight variation per day. Popular for intermediate trainees and those prioritising strength.",
        "frequency_note": "3x/week per muscle — high frequency, good for skill development",
        "is_recommended": False,
        "days": [
            {"day_number": 1, "name": "Full Body A", "muscle_focus": ALL_MUSCLES},
            {"day_number": 2, "name": "Full Body B", "muscle_focus": ALL_MUSCLES},
            {"day_number": 3, "name": "Full Body C", "muscle_focus": ALL_MUSCLES},
        ],
    },
    {
        "name": "Push / Pull / Legs 3x",
        "slug": "ppl_3",
        "days_per_week": 3,
        "split_type": "ppl",
        "description": "Classic PPL run once per week. Each session focuses on either pushing muscles, pulling muscles, or legs for clean separation.",
        "frequency_note": "1x/week per muscle — low frequency PPL",
        "is_recommended": False,
        "days": [
            {"day_number": 1, "name": "Push", "muscle_focus": ["chest", "shoulders", "triceps"]},
            {"day_number": 2, "name": "Pull", "muscle_focus": ["back", "lats", "biceps", "traps"]},
            {"day_number": 3, "name": "Legs", "muscle_focus": ["quads", "hamstrings", "glutes", "calves"]},
        ],
    },
    {
        "name": "Arnold 3x",
        "slug": "arnold_3",
        "days_per_week": 3,
        "split_type": "bro",
        "description": "Arnold Schwarzenegger's classic 3-day split pairing opposing muscle groups. A timeless approach used by golden-era bodybuilders.",
        "frequency_note": "1x/week per muscle — classic bodybuilding structure",
        "is_recommended": False,
        "days": [
            {"day_number": 1, "name": "Chest & Back", "muscle_focus": ["chest", "back", "lats"]},
            {"day_number": 2, "name": "Shoulders & Arms", "muscle_focus": ["shoulders", "biceps", "triceps"]},
            {"day_number": 3, "name": "Legs", "muscle_focus": ["quads", "hamstrings", "glutes", "calves"]},
        ],
    },
    {
        "name": "Upper / Lower / Full Body 3x",
        "slug": "upper_lower_fb_3",
        "days_per_week": 3,
        "split_type": "hybrid",
        "description": "Combines an upper day, lower day, and full-body day for flexible weekly structure. Good for 3-day schedules wanting more variety.",
        "frequency_note": "1-2x/week per muscle — hybrid approach",
        "is_recommended": False,
        "days": [
            {"day_number": 1, "name": "Upper", "muscle_focus": ["chest", "back", "shoulders", "biceps", "triceps"]},
            {"day_number": 2, "name": "Lower", "muscle_focus": ["quads", "hamstrings", "glutes", "calves"]},
            {"day_number": 3, "name": "Full Body", "muscle_focus": ALL_MUSCLES},
        ],
    },
    {
        "name": "Upper / Lower 4x",
        "slug": "upper_lower_4",
        "days_per_week": 4,
        "split_type": "upper_lower",
        "description": "The gold standard for hypertrophy. Each muscle group trained twice per week with strength-focused A sessions and volume-focused B sessions.",
        "frequency_note": "2x/week per muscle — gold standard for hypertrophy",
        "is_recommended": True,
        "days": [
            {"day_number": 1, "name": "Upper A", "muscle_focus": ["chest", "back", "shoulders", "biceps", "triceps"]},
            {"day_number": 2, "name": "Lower A", "muscle_focus": ["quads", "hamstrings", "glutes", "calves"]},
            {"day_number": 3, "name": "Upper B", "muscle_focus": ["chest", "back", "shoulders", "biceps", "triceps"]},
            {"day_number": 4, "name": "Lower B", "muscle_focus": ["quads", "hamstrings", "glutes", "calves"]},
        ],
    },
    {
        "name": "PHUL 4x",
        "slug": "phul_4",
        "days_per_week": 4,
        "split_type": "phul",
        "description": "Power Hypertrophy Upper Lower — two power days for strength and two hypertrophy days for size. Great for intermediate lifters wanting both.",
        "frequency_note": "2x/week per muscle — power + hypertrophy blend",
        "is_recommended": False,
        "days": [
            {"day_number": 1, "name": "Upper Power", "muscle_focus": ["chest", "back", "shoulders", "biceps", "triceps"]},
            {"day_number": 2, "name": "Lower Power", "muscle_focus": ["quads", "hamstrings", "glutes"]},
            {"day_number": 3, "name": "Upper Hypertrophy", "muscle_focus": ["chest", "back", "shoulders", "biceps", "triceps"]},
            {"day_number": 4, "name": "Lower Hypertrophy", "muscle_focus": ["quads", "hamstrings", "glutes", "calves"]},
        ],
    },
    {
        "name": "PPL + Full Body 4x",
        "slug": "ppl_fb_4",
        "days_per_week": 4,
        "split_type": "hybrid",
        "description": "Standard PPL with a bonus full-body day. Good for those who want push/pull/legs structure with extra overall frequency.",
        "frequency_note": "1-2x/week per muscle — PPL with added full-body day",
        "is_recommended": False,
        "days": [
            {"day_number": 1, "name": "Push", "muscle_focus": ["chest", "shoulders", "triceps"]},
            {"day_number": 2, "name": "Pull", "muscle_focus": ["back", "lats", "biceps"]},
            {"day_number": 3, "name": "Legs", "muscle_focus": ["quads", "hamstrings", "glutes", "calves"]},
            {"day_number": 4, "name": "Full Body", "muscle_focus": ALL_MUSCLES},
        ],
    },
    {
        "name": "Bro Split 4x",
        "slug": "bro_4",
        "days_per_week": 4,
        "split_type": "bro",
        "description": "Classic bodybuilder split dedicating each day to one or two muscle groups. Low frequency but high per-session volume.",
        "frequency_note": "1x/week per muscle — traditional bodybuilding bro split",
        "is_recommended": False,
        "days": [
            {"day_number": 1, "name": "Chest & Triceps", "muscle_focus": ["chest", "triceps"]},
            {"day_number": 2, "name": "Back & Biceps", "muscle_focus": ["back", "lats", "biceps"]},
            {"day_number": 3, "name": "Shoulders", "muscle_focus": ["shoulders", "traps"]},
            {"day_number": 4, "name": "Legs", "muscle_focus": ["quads", "hamstrings", "glutes", "calves"]},
        ],
    },
    {
        "name": "UL / PPL 5x",
        "slug": "ulppl_5",
        "days_per_week": 5,
        "split_type": "hybrid",
        "description": "A hybrid of upper/lower and PPL across 5 days. Provides excellent muscle frequency with manageable per-session volume.",
        "frequency_note": "2x/week per muscle — excellent frequency/volume balance",
        "is_recommended": True,
        "days": [
            {"day_number": 1, "name": "Upper", "muscle_focus": ["chest", "back", "shoulders", "biceps", "triceps"]},
            {"day_number": 2, "name": "Lower", "muscle_focus": ["quads", "hamstrings", "glutes", "calves"]},
            {"day_number": 3, "name": "Push", "muscle_focus": ["chest", "shoulders", "triceps"]},
            {"day_number": 4, "name": "Pull", "muscle_focus": ["back", "lats", "biceps"]},
            {"day_number": 5, "name": "Legs", "muscle_focus": ["quads", "hamstrings", "glutes", "calves"]},
        ],
    },
    {
        "name": "PHAT 5x",
        "slug": "phat_5",
        "days_per_week": 5,
        "split_type": "phat",
        "description": "Power Hypertrophy Adaptive Training by Layne Norton. Two power days followed by three hypertrophy days for optimal strength and size.",
        "frequency_note": "2x/week per muscle — advanced power/hypertrophy integration",
        "is_recommended": False,
        "days": [
            {"day_number": 1, "name": "Upper Power", "muscle_focus": ["chest", "back", "shoulders", "biceps", "triceps"]},
            {"day_number": 2, "name": "Lower Power", "muscle_focus": ["quads", "hamstrings", "glutes"]},
            {"day_number": 3, "name": "Back & Shoulders Hyp", "muscle_focus": ["back", "lats", "shoulders", "traps"]},
            {"day_number": 4, "name": "Lower Hypertrophy", "muscle_focus": ["quads", "hamstrings", "glutes", "calves"]},
            {"day_number": 5, "name": "Chest & Arms Hyp", "muscle_focus": ["chest", "biceps", "triceps"]},
        ],
    },
    {
        "name": "Bro Split 5x",
        "slug": "bro_5",
        "days_per_week": 5,
        "split_type": "bro",
        "description": "Five-day bodybuilder split with each muscle group getting its own dedicated day. Maximum per-session volume for each muscle.",
        "frequency_note": "1x/week per muscle — high volume, low frequency classic bro split",
        "is_recommended": False,
        "days": [
            {"day_number": 1, "name": "Chest", "muscle_focus": ["chest", "triceps"]},
            {"day_number": 2, "name": "Back", "muscle_focus": ["back", "lats", "biceps"]},
            {"day_number": 3, "name": "Shoulders", "muscle_focus": ["shoulders", "traps"]},
            {"day_number": 4, "name": "Arms", "muscle_focus": ["biceps", "triceps", "forearms"]},
            {"day_number": 5, "name": "Legs", "muscle_focus": ["quads", "hamstrings", "glutes", "calves"]},
        ],
    },
]

LANDMARKS = [
    # (goal, muscle, mev, mav_low, mav_high, mrv)

    # hypertrophy — maximize muscle growth, bodybuilder-level volume
    ("hypertrophy", "chest",       8,  12, 20, 22),
    ("hypertrophy", "back",        10, 14, 22, 25),
    ("hypertrophy", "quads",       8,  12, 20, 20),
    ("hypertrophy", "hamstrings",  6,  10, 16, 20),
    ("hypertrophy", "glutes",      0,  4,  12, 16),
    ("hypertrophy", "shoulders",   8,  16, 22, 26),
    ("hypertrophy", "biceps",      8,  14, 20, 26),
    ("hypertrophy", "triceps",     6,  10, 14, 18),
    ("hypertrophy", "calves",      8,  12, 16, 20),
    ("hypertrophy", "abs",         0,  6,  16, 20),
    ("hypertrophy", "lats",        10, 14, 22, 25),
    ("hypertrophy", "traps",       8,  12, 20, 22),

    # general_fitness — athletic, built, functional; think Evander Holyfield / Chris Evans
    # strength-leaning, 6-12 hard sets/muscle/week is the target
    ("general_fitness", "chest",       4,  6,  12, 16),
    ("general_fitness", "back",        4,  6,  12, 16),
    ("general_fitness", "quads",       4,  6,  12, 15),
    ("general_fitness", "hamstrings",  3,  5,  10, 14),
    ("general_fitness", "glutes",      0,  3,   8, 12),
    ("general_fitness", "shoulders",   4,  8,  14, 18),
    ("general_fitness", "biceps",      3,  5,  10, 14),
    ("general_fitness", "triceps",     3,  5,   8, 12),
    ("general_fitness", "calves",      4,  6,  10, 14),
    ("general_fitness", "abs",         0,  4,  10, 14),
    ("general_fitness", "lats",        4,  6,  12, 16),
    ("general_fitness", "traps",       3,  5,  10, 12),

    # strength — powerlifting/strength focus; low volume, high intensity, compound-heavy
    ("strength", "chest",       3,  4,   8, 12),
    ("strength", "back",        4,  6,  10, 14),
    ("strength", "quads",       4,  5,  10, 14),
    ("strength", "hamstrings",  3,  4,   8, 12),
    ("strength", "glutes",      0,  2,   6, 10),
    ("strength", "shoulders",   3,  4,   8, 12),
    ("strength", "biceps",      2,  3,   6,  8),
    ("strength", "triceps",     3,  4,   8, 10),
    ("strength", "calves",      3,  4,   8, 10),
    ("strength", "abs",         0,  3,   8, 12),
    ("strength", "lats",        4,  6,  10, 14),
    ("strength", "traps",       3,  4,   8, 10),

    # recomp — body recomposition; moderate volume, mixed stimulus
    ("recomp", "chest",       6,  10, 16, 20),
    ("recomp", "back",        7,  11, 18, 22),
    ("recomp", "quads",       6,  10, 16, 18),
    ("recomp", "hamstrings",  5,   8, 13, 18),
    ("recomp", "glutes",      0,   3,  9, 14),
    ("recomp", "shoulders",   6,  12, 18, 22),
    ("recomp", "biceps",      6,  10, 16, 22),
    ("recomp", "triceps",     5,   8, 11, 16),
    ("recomp", "calves",      6,  10, 13, 18),
    ("recomp", "abs",         0,   5, 13, 18),
    ("recomp", "lats",        7,  11, 18, 22),
    ("recomp", "traps",       6,  10, 16, 20),
]
# fmt: on


def _build_substitution_map(exercises: list[dict]) -> dict[str, list[int]]:
    """
    Build substitution_ids by grouping exercises that share the same
    primary muscle group and movement mechanics.  Within each group,
    every exercise substitutes every other exercise in the group.
    IDs are 1-based (matching the order of insertion).
    """
    groups: dict[str, list[int]] = {}
    for idx, ex in enumerate(exercises, start=1):
        pm = ex["primary_muscles"][0] if ex["primary_muscles"] else "other"
        mech = ex["mechanics"]
        key = f"{pm}_{mech}"
        groups.setdefault(key, []).append(idx)

    subs: dict[str, list[int]] = {}
    for idx, ex in enumerate(exercises, start=1):
        pm = ex["primary_muscles"][0] if ex["primary_muscles"] else "other"
        mech = ex["mechanics"]
        key = f"{pm}_{mech}"
        subs[str(idx)] = [i for i in groups[key] if i != idx]

    return subs


def _compute_sub_pattern(movement_pattern: str, force: str, primary_muscles: list, mechanics: str, name: str) -> str:
    """Derive the slot sub_pattern from existing exercise fields. Used at seed time and for backfill."""
    name_lower = name.lower()

    if movement_pattern == "hinge":
        return "hip_dominant"

    if movement_pattern == "squat":
        return "knee_dominant"

    if movement_pattern == "core":
        return "core"

    if movement_pattern == "isolation":
        return ""

    if movement_pattern == "push":
        # Leg press: push movement but knee-dominant pattern
        if any(m in ("quads", "glutes", "hamstrings") for m in primary_muscles) and "chest" not in primary_muscles:
            return "knee_dominant"
        # Tricep-primary or isolation mechanics → accessory
        if mechanics == "isolation":
            return ""
        if primary_muscles and primary_muscles[0] == "triceps":
            return ""
        # Vertical push: shoulder-primary compounds (OHP, Arnold, Push Press)
        if any(m in ("shoulders", "deltoids") for m in primary_muscles):
            return "vertical_push"
        # Horizontal push: chest-primary compounds
        if any(m in ("chest",) for m in primary_muscles):
            return "horizontal_push"
        return "horizontal_push"

    if movement_pattern == "pull":
        # Curl / isolation → accessory
        if mechanics == "isolation":
            return ""
        if primary_muscles and primary_muscles[0] == "biceps":
            return ""
        # Rear-delt / shoulder compound with no back/lats → isolation-equivalent
        if (any(m in ("rear_delts", "shoulders", "traps") for m in primary_muscles)
                and not any(m in ("back", "lats") for m in primary_muscles)):
            return ""
        # Vertical pull by name
        if any(w in name_lower for w in ("pull-up", "pullup", "pull up", "chin-up", "chinup", "pulldown", "pull-down")):
            return "vertical_pull"
        # Lats-only primary without back label → vertical
        if primary_muscles and primary_muscles[0] == "lats" and "back" not in primary_muscles:
            return "vertical_pull"
        # Back/lats → horizontal pull (rows)
        if any(m in ("back", "lats") for m in primary_muscles):
            return "horizontal_pull"
        return ""

    return ""


def seed(session: Session) -> None:
    subs_map = _build_substitution_map(EXERCISES)
    for idx, ex_data in enumerate(EXERCISES, start=1):
        sub_pat = _compute_sub_pattern(
            ex_data["movement_pattern"],
            ex_data["force"],
            ex_data["primary_muscles"],
            ex_data["mechanics"],
            ex_data["name"],
        )
        ex = Exercise(
            name=ex_data["name"],
            aliases=json.dumps(ex_data.get("aliases", [])),
            movement_pattern=ex_data["movement_pattern"],
            primary_muscles=json.dumps(ex_data["primary_muscles"]),
            secondary_muscles=json.dumps(ex_data.get("secondary_muscles", [])),
            equipment_required=json.dumps(ex_data["equipment_required"]),
            mechanics=ex_data["mechanics"],
            force=ex_data["force"],
            is_bilateral=ex_data["is_bilateral"],
            notes=ex_data.get("notes", ""),
            substitution_ids=json.dumps(subs_map.get(str(idx), [])),
            is_custom=False,
            sub_pattern=sub_pat,
        )
        session.add(ex)
    session.commit()
    print(f"Seeded {len(EXERCISES)} exercises.")


def seed_splits(session: Session) -> None:
    for split_data in SPLITS:
        template = SplitTemplate(
            name=split_data["name"],
            slug=split_data["slug"],
            days_per_week=split_data["days_per_week"],
            split_type=split_data["split_type"],
            description=split_data["description"],
            frequency_note=split_data["frequency_note"],
            is_builtin=True,
            is_recommended=split_data.get("is_recommended", False),
        )
        session.add(template)
        session.commit()
        session.refresh(template)

        for day_data in split_data["days"]:
            day = SplitDay(
                template_id=template.id,
                day_number=day_data["day_number"],
                name=day_data["name"],
                muscle_focus=json.dumps(day_data["muscle_focus"]),
            )
            session.add(day)
        session.commit()
    print(f"Seeded {len(SPLITS)} split templates.")


def seed_landmarks(session: Session) -> None:
    for goal, muscle, mev, mav_low, mav_high, mrv in LANDMARKS:
        landmark = MuscleVolumeLandmark(
            user_id=1,
            goal=goal,
            muscle=muscle,
            mev=mev,
            mav_low=mav_low,
            mav_high=mav_high,
            mrv=mrv,
        )
        session.add(landmark)
    session.commit()
    print(f"Seeded {len(LANDMARKS)} volume landmarks across all goals.")


if __name__ == "__main__":
    create_db_and_tables()
    from sqlmodel import Session, select

    with Session(engine) as s:
        count = s.exec(select(Exercise)).all()
        if count:
            print("Exercises already seeded.")
        else:
            seed(s)

        split_count = s.exec(select(SplitTemplate)).all()
        if split_count:
            print("Splits already seeded.")
        else:
            seed_splits(s)

        landmark_count = s.exec(select(MuscleVolumeLandmark)).all()
        if landmark_count:
            print("Landmarks already seeded.")
        else:
            seed_landmarks(s)
